import type { APIRequestContext } from "@playwright/test";
import { expect, test } from "./fixtures";

const origin = "http://localhost:3100", headers = { Origin: origin };
async function addRecipe(request: APIRequestContext, title: string, ingredients: string[]) {
  const response = await request.post(`${origin}/api/recipes`, { headers, data: { content: {
    title, servings: 4, totalMinutes: 30,
    ingredientSections: [{ items: ingredients.map((text) => ({ text })) }],
    instructionSections: [{ steps: ["Cook and serve."] }],
  } } });
  expect(response.status()).toBe(201);
  return await response.json() as { id: string };
}

test("shop directly from recipes, switch lists, filter ingredients, undo clearing, copy formats, and delete a finished list", async ({ page }, testInfo) => {
  const signup = await page.request.post(`${origin}/api/auth/sign-up/email`, { headers, data: { name: "Robin", email: `shopping-${crypto.randomUUID()}@example.test`, password: "a-good-test-password-42" } });
  expect(signup.ok()).toBe(true);
  const chili = await addRecipe(page.request, "Turkey Chili", ["2 onions", "1 tbsp olive oil", "1 can beans"]);
  const soup = await addRecipe(page.request, "Onion Soup", ["1 onion", "2 tbsp olive oil", "salt"]);

  await page.goto(`/recipes/${chili.id}`);
  await expect(page.getByRole("navigation", { name: "Kitchen modes" }).getByRole("link", { name: "Plan", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Add to shopping list", exact: true }).click();
  await page.getByRole("textbox", { name: "List name" }).fill("Weekly groceries");
  await page.getByRole("button", { name: "Create list & add recipe", exact: true }).click();
  await expect(page.getByRole("button", { name: "Added to Weekly groceries", exact: true })).toBeDisabled();
  await page.goto(`/recipes/${soup.id}`);
  await page.getByRole("button", { name: "Add to Weekly groceries", exact: true }).click();
  await expect(page.getByRole("button", { name: "Added to Weekly groceries", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Choose shopping list" }).click();
  await page.getByRole("menuitem", { name: "New shopping list" }).click();
  await page.getByRole("textbox", { name: "List name" }).fill("Dinner party");
  await page.getByRole("button", { name: "Create list & add recipe", exact: true }).click();
  await expect(page.getByRole("button", { name: "Added to Dinner party" })).toBeDisabled();
  await page.getByRole("button", { name: "Choose shopping list" }).click();
  await page.getByRole("menuitem", { name: "Weekly groceries", exact: true }).click();
  await expect(page.getByRole("button", { name: "Added to Weekly groceries" })).toBeDisabled();
  await page.getByRole("button", { name: "Choose shopping list" }).click();
  await page.getByRole("menuitem", { name: "Open Weekly groceries" }).click();
  await expect(page.getByRole("heading", { name: "Weekly groceries" })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "3 onions", exact: true })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "3 tbsp olive oil", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Add items", exact: true }).click();
  await page.getByRole("textbox", { name: "Items, one per line" }).fill("Paper towels");
  await page.getByRole("combobox", { name: "Category (optional)" }).selectOption("Household");
  await page.getByRole("button", { name: "Save items" }).click();
  await expect(page.getByRole("button", { name: "Edit Paper towels", exact: true })).toHaveText("Household");
  await page.getByRole("checkbox", { name: "Paper towels" }).check();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeEnabled();
  await expect(page.getByRole("button", { name: "Add recipes", exact: true })).toHaveCount(0);
  await expect(page.getByRole("table", { name: "Shopping items" })).toBeVisible();
  await page.getByRole("button", { name: "Edit 3 onions", exact: true }).click();
  await page.getByRole("combobox", { name: "Category (optional)" }).fill("Produce");
  await page.getByRole("button", { name: "Save item", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit 3 onions", exact: true })).toHaveText("Produce");
  await page.getByRole("button", { name: "Edit Paper towels", exact: true }).click();
  await page.getByRole("combobox", { name: "Category (optional)" }).fill("Household");
  await page.getByRole("button", { name: "Save item", exact: true }).click();
  await page.getByRole("button", { name: "Sort by category", exact: true }).click();
  await expect(page.getByRole("table", { name: "Shopping items" }).getByRole("row").nth(1)).toContainText("Paper towels");
  await page.getByRole("button", { name: "Restore list order", exact: true }).click();
  if (testInfo.project.name === "phone") await page.screenshot({ path: "/private/tmp/sift-shopping-phone.png" });
  await page.getByRole("button", { name: "Store mode", exact: true }).click();
  const store = page.getByRole("dialog");
  await store.getByRole("button", { name: "Produce", exact: true }).click();
  await expect(store.getByRole("checkbox", { name: "1 can beans", exact: true })).toHaveCount(0);
  await store.getByRole("checkbox", { name: "3 onions", exact: true }).check();
  await store.getByRole("button", { name: "Clear checked", exact: true }).click();
  await expect(store.getByRole("checkbox", { name: "3 onions", exact: true })).toHaveCount(0);
  await store.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(store.getByRole("checkbox", { name: "3 onions", exact: true })).toBeChecked();
  await store.getByRole("checkbox", { name: "3 onions", exact: true }).uncheck();
  await store.getByRole("button", { name: "All", exact: true }).click();
  await expect(store.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  const storeBounds = await store.boundingBox(), viewport = page.viewportSize()!;
  expect(storeBounds?.width).toBe(viewport.width);
  expect(storeBounds?.height).toBe(viewport.height);
  if (testInfo.project.name === "phone") await page.screenshot({ path: "/private/tmp/sift-store-phone.png" });
  await store.getByRole("button", { name: "List view", exact: true }).click();
  await expect(store).toHaveCount(0);
  await expect(page.getByRole("checkbox", { name: "3 onions", exact: true })).not.toBeChecked();
  await page.getByRole("button", { name: "Filter by Onion Soup", exact: true }).click();
  await expect(page.getByRole("button", { name: "Filter by Onion Soup", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("checkbox", { name: "1 can beans", exact: true })).toHaveCount(0);
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toHaveCount(0);
  await expect(page.getByRole("checkbox", { name: "3 onions", exact: true })).toBeVisible();
  await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.getByRole("button", { name: "Copy format", exact: true }).click();
  await page.getByRole("menuitem", { name: "Markdown", exact: true }).click();
  await expect(page.getByRole("button", { name: "Copied", exact: true })).toBeVisible();
  let copied = await page.evaluate(() => navigator.clipboard.readText());
  expect(copied).toContain("# Weekly groceries");
  expect(copied).toContain("- [ ] 3 onions");
  expect(copied).not.toContain("beans");
  await page.getByRole("checkbox", { name: "3 onions", exact: true }).check();
  await page.getByRole("button", { name: "Clear checked", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "3 onions", exact: true })).toHaveCount(0);
  await expect(page.getByRole("status").filter({ hasText: "1 item cleared" })).toBeVisible();
  const toastBackground = await page.getByRole("status").filter({ hasText: "1 item cleared" }).evaluate((element) => getComputedStyle(element.parentElement!).backgroundColor);
  expect(toastBackground).toMatch(/^rgb\(/);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "3 onions", exact: true })).toBeChecked();
  await expect(page.getByRole("button", { name: "Edit 3 onions", exact: true })).toHaveText("Produce");
  await page.getByRole("button", { name: "Show all", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await page.getByRole("button", { name: "Remove Paper towels", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toHaveCount(0);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await page.getByRole("button", { name: "Copy list", exact: true }).click();
  await expect(page.getByRole("button", { name: "Copied", exact: true })).toBeVisible();
  copied = await page.evaluate(() => navigator.clipboard.readText());
  expect(copied).toContain("[x] Paper towels");
  expect(copied).not.toContain("# Weekly groceries");
  await page.getByRole("button", { name: "Remove Turkey Chili from list" }).click();
  await expect(page.getByRole("checkbox", { name: "1 onion", exact: true })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await page.reload();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await page.getByRole("button", { name: "Shopping list options" }).click();
  await page.getByRole("menuitem", { name: "Rename", exact: true }).click();
  await page.getByRole("textbox", { name: "List name" }).fill("Finished week");
  await page.getByRole("button", { name: "Save name" }).click();
  await expect(page.getByRole("heading", { name: "Finished week", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Archive list", exact: true }).click();
  await expect(page.getByText("Archived list", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Add items", exact: true })).toBeDisabled();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await page.goto(`/recipes/${soup.id}`);
  await expect(page.getByRole("button", { name: "Added to Dinner party" })).toBeDisabled();
  await page.getByRole("button", { name: "Choose shopping list" }).click();
  await expect(page.getByRole("menuitem", { name: "Finished week", exact: true })).toHaveCount(0);
  await page.goto("/library?mode=shop");
  await expect(page.getByRole("heading", { name: "Finished week", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Archived", exact: true }).click();
  const archivedCard = page.getByRole("article", { name: "Finished week shopping list" });
  await expect(archivedCard).toBeVisible();
  await archivedCard.getByRole("button", { name: "Restore list", exact: true }).click();
  await expect(archivedCard).toHaveCount(0);
  await page.getByRole("button", { name: "Active", exact: true }).click();
  await page.getByRole("article", { name: "Finished week shopping list" }).getByRole("link").click();
  await expect(page.getByRole("checkbox", { name: "Paper towels" })).toBeChecked();
  await expect(page.getByRole("button", { name: "Edit Paper towels", exact: true })).toHaveText("Household");
  await expect(page.getByRole("button", { name: "Add items", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Shopping list options" }).click();
  await page.getByRole("menuitem", { name: "Delete list", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Delete list", exact: true }).click();
  await expect(page).toHaveURL(/\/library\?mode=shop/);
  await expect(page.getByRole("heading", { name: "Dinner party", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Finished week", exact: true })).toHaveCount(0);
  await page.goto(`/recipes/${soup.id}`);
  await expect(page.getByRole("button", { name: "Added to Dinner party" })).toBeDisabled();
});
