"use client";
import Link from "next/link";
import { X } from "lucide-react";
import type { ArtifactDetail } from "@/domain/artifact";
import { Button } from "./ui/button";
import type { ArtifactAction } from "./use-artifact";

type Mutate = (action: ArtifactAction, optimistic?: (value: ArtifactDetail) => ArtifactDetail) => Promise<boolean>;
export function ArtifactContents({ artifact, busy, mutate, compact = false, onNavigate }: { artifact: ArtifactDetail; busy: boolean; mutate: Mutate; compact?: boolean; onNavigate?: () => void }) {
  if (artifact.content.kind === "grocery") {
    const groups = artifact.content.groups.map((group, index, all) => ({ ...group, items: group.items.slice(0, compact ? Math.max(0, 6 - all.slice(0, index).reduce((count, before) => count + before.items.length, 0)) : undefined) })).filter((group) => group.items.length);
    const total = artifact.content.groups.reduce((count, group) => count + group.items.length, 0);
    return <div className={compact ? "space-y-3" : "space-y-8"}>{!total && <p className="py-4 text-sm text-muted-foreground">Your list is ready for its first item.</p>}{groups.map((group) => <section key={group.id}>{group.name && <h2 className={`mb-2 font-medium ${compact ? "text-xs text-muted-foreground" : "text-base"}`}>{group.name}</h2>}<ul className="divide-y">{group.items.map((item) => <li key={item.id} className="flex items-start gap-2"><label className="flex min-h-12 min-w-0 flex-1 cursor-pointer items-start gap-3 py-3"><input type="checkbox" checked={item.checked} disabled={busy} className="mt-0.5 size-5 shrink-0 accent-foreground" onChange={(event) => { void mutate({ action: "checkItem", itemId: item.id, checked: event.target.checked }, (value) => value.content.kind === "grocery" ? { ...value, content: { ...value.content, groups: value.content.groups.map((group) => ({ ...group, items: group.items.map((entry) => entry.id === item.id ? { ...entry, checked: !item.checked } : entry) })) } } : value); }} /><span className={`min-w-0 break-words leading-relaxed ${compact ? "text-sm" : "text-base"} ${item.checked ? "text-muted-foreground line-through" : ""}`}>{item.text}</span></label>{!compact && <Button variant="ghost" size="icon" disabled={busy} aria-label={`Remove ${item.text}`} className="mt-1 shrink-0 text-muted-foreground" onClick={() => { void mutate({ action: "removeItem", itemId: item.id }, (value) => value.content.kind === "grocery" ? { ...value, content: { ...value.content, groups: value.content.groups.map((group) => ({ ...group, items: group.items.filter((entry) => entry.id !== item.id) })) } } : value); }}><X /></Button>}</li>)}</ul></section>)}{compact && total > 6 && <p className="text-xs text-muted-foreground">{total - 6} more items in the full list</p>}</div>;
  }
  const entries = compact ? artifact.content.entries.slice(0, 3) : artifact.content.entries;
  return <div className={compact ? "space-y-3" : "space-y-4"}>{!entries.length && <p className="py-4 text-sm text-muted-foreground">Start with one meal. The rest can follow.</p>}{entries.map((entry) => <article key={entry.id} className={compact ? "border-t pt-3" : "rounded-2xl border p-5"}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">{entry.date ? `${new Date(`${entry.date}T00:00:00Z`).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" })} · ` : ""}{entry.meal}{entry.servings ? ` · ${entry.servings} servings` : ""}</p><h2 className={`mt-2 break-words font-medium ${compact ? "text-sm" : "text-lg"}`}>{entry.title}</h2></div>{!compact && <Button variant="ghost" size="icon" aria-label={`Remove ${entry.title}`} disabled={busy} className="shrink-0 text-muted-foreground" onClick={() => { void mutate({ action: "removeEntry", entryId: entry.id }, (value) => value.content.kind === "meal-plan" ? { ...value, content: { ...value.content, entries: value.content.entries.filter((meal) => meal.id !== entry.id) } } : value); }}><X /></Button>}</div>{entry.note && <p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-muted-foreground">{compact ? entry.note.slice(0, 150) : entry.note}</p>}{entry.recipeId && <Link href={`/recipes/${entry.recipeId}`} onClick={onNavigate} className="mt-2 inline-flex min-h-10 items-center text-xs underline underline-offset-4">Open recipe</Link>}</article>)}{compact && artifact.content.entries.length > 3 && <p className="text-xs text-muted-foreground">{artifact.content.entries.length - 3} more meals in the full plan</p>}</div>;
}
